---
# tasks file for roles/error-debugging
- name: Check if a file exists in temp and fail task if it does
  command: ls /tmp/this_should_not_be_here
  register: result
  failed_when:
    - result.rc == 0
    - '"No such" not in result.stdout'
- name: copy result to a local file
  local_action:
    module: copy 
    content: "{{ result }}"
    dest: "{{error_dir}}{{error_filename}}"