
# install-services.yml

---
  - hosts: aworker
    become: true
    tasks:
      - name: Installing packages
        apt:
          pkg: 
            - git
            - python3
            - python3-dev
            - python3-pip
            - nginx
          state: present