# check-status.yml
---
  - hosts: aworker
    tasks:
      - name: Confirm that 200 OK response is returned
        uri:
          url: "https://public.opendatasoft.com/api/records/1.0/search/?dataset=georef-germany-postleitzahl&q=&facet=note&facet=plz_code&refine.plz_code={{ zipcode }}"
          return_content: yes
          #status_code: 200
          #body_format: json
          follow_redirects: all
        register: result
      
      - name: display result
        debug:
          msg: "{{result.json.records[0].fields.plz_name}}"