---
# tasks file for roles/nginx-konfigurierende

- name: Creating nginx config from template
  become: true
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0755'
    group: "root"
    owner: "root"

- name: Create a directory if it does not exist
  become: true
  file:
    path: "{{rootdir}}{{ item }}"
    state: directory
    mode: '0755'
    group: "www-data"
    owner: "www-data"
  loop:  "{{ locations }}"
      
- name: Creating index.html fro locations via jinja
  become: true
  template:
    src: ../templates/index.html.j2
    dest: "{{rootdir}}{{ item }}/index.html"
    mode: '0755'
    group: "www-data"
    owner: "www-data"
  loop: "{{ locations }}"

- name: restart nginx
  service: name=nginx state=restarted 
  become: true